redis:
  image: redis
  ports:
    - '6379:6379'

db:
  image: mysql
  ports:
    - '3306:3306'
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=sesholder

app:
  build: .
  ports:
    - '80:80'
  links:
    - db
    - redis
  environment:
    - RAILS_ENV=production
    - SECRET_KEY_BASE=61a6fa38260a0fdfecac5c088aadd91e87
