default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: sesholder_development

test:
  <<: *default
  database: sesholder_test

production:
  <<: *default
  database: sesholder
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] || ENV['DB_HOST'] %>
  password: <%= ENV['DB_ENV_MYSQL_ROOT_PASSWORD'] || ENV['DB_PASSWORD'] %>
